app = "telegram-bot-danaharia2"

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  
  [[services.ports]]
    port = 8080
  
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    path = "/"