# railway.toml
[build]
  builder = "nixpacks"

[deploy]
  startCommand = "python main.py"

[environments]
  [environments.production]
    [environments.production.variables]
      NODE_ENV = "production"